# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: search_account_rsp.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'search_account_rsp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18search_account_rsp.proto\"3\n\x0b\x41\x63\x63ountInfo\x12\x12\n\naccount_id\x18\x01 \x01(\x03\x12\x10\n\x08nickname\x18\x03 \x01(\t\"?\n\x1dSCFuzzySearchAccountByNameRsp\x12\x1e\n\x08\x61\x63\x63ounts\x18\x01 \x03(\x0b\x32\x0c.AccountInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_account_rsp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCOUNTINFO']._serialized_start=28
  _globals['_ACCOUNTINFO']._serialized_end=79
  _globals['_SCFUZZYSEARCHACCOUNTBYNAMERSP']._serialized_start=81
  _globals['_SCFUZZYSEARCHACCOUNTBYNAMERSP']._serialized_end=144
# @@protoc_insertion_point(module_scope)

